# Tomcat settings
server:
  port: ${UNDERTOW_SERVER_PORT:8080}
  undertow:
    io-threads: 1
    worker-threads: 8
    buffer-size: 1024

# Management settings
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Logging settings
logging:
  level:
    root: WARN
    org:
      springframework:
        security: INFO
        web: ERROR
      hibernate: INFO
    com:
      github: DEBUG
  file:
    path: ${LOGGING_FILE_PATH:./}
    name: output.log
    max-size: ${LOGGING_FILE_MAX_SIZE:20MB}
    max-history: ${LOGGING_FILE_MAX_HISTORY:100}

# Spring settings
spring:
  profiles:
    active: dev
  application:
    name: quartz-cluster
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testdb?useSSL=false&characterEncoding=utf8&useUnicode=true&zeroDateTimeBehavior=convertToNull
    username: testdb
    password: testdb
    driver-class-name: com.mysql.jdbc.Driver
#    druid:
#      initial-size: 5
#      max-active: 20
#      min-idle: 5
#      max-wait: 60000
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      max-open-prepared-statements: 20
#      validation-query: SELECT 1 FROM DUAL
#      test-on-borrow: false
#      test-on-return: false
#      test-while-idle: true
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      filters: stat,wall

