# Tomcat settings
server:
  port: ${UNDERTOW_SERVER_PORT:8080}
  undertow:
    io-threads: 1
    worker-threads: 8
    buffer-size: 1024

# Management settings
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Logging settings
logging:
  level:
    root: WARN
    org:
      springframework:
        security: INFO
        web: ERROR
      hibernate: INFO
    com:
      github: INFO
  file:
    path: ${LOGGING_FILE_PATH:./}
    name: output.log
    max-size: ${LOGGING_FILE_MAX_SIZE:500MB}
    max-history: ${LOGGING_FILE_MAX_HISTORY:7}
    total-size-cap: ${LOGGING_FILE_TOTAL_SIZE:1500MB}
  pattern:
    rolling-file-name: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.log"

# Spring settings
spring:
  profiles:
    active: dev
  application:
    name: quartz-simple
